config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "sleep_ms#index"
  resources :sleep_ms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sleep_m.rb
class SleepM < ApplicationRecord
  enum quality: {普通: "normal", 良: "good", 最高: "excellent", 悪い: "bad" }
  belongs_to :user
  def sleep_duration_minutes
    ((end_time - set_time) / 60).to_i
  end
  def sleep_duration
    (end_time - set_time) / 1.hour  
  end
  validates :quality, presence: true
  validates :set_time, presence: true
  validates :end_time, presence: true
  validate :start_time_must_be_earlier_than_end_time
  validate :date_must_be_today_or_earlier
  validate :no_overlapping_records

  private

  def start_time_must_be_earlier_than_end_time
    return unless set_time && end_time
    if set_time >= end_time
      errors.add(:set_time, "は終了時間よりも早い時間に設定してください")
    end
  end

  def date_must_be_today_or_earlier
    return unless set_time

    if set_time.to_date > Date.tomorrow
      errors.add(:set_time, "は今日までの日にちを選択してください")
    end
  end

  def no_overlapping_records
    if overlaps_existing_record?
      errors.add(:base, "同じ時間帯に記録が既に存在します")
    end
  end

  def overlaps_existing_record?
    existing_records = SleepM.where.not(id: self.id)
    existing_records.any? { |record| overlaps?(record) }
  end

  def overlaps?(other_record)
    (self.set_time <= other_record.end_time) && (self.end_time >= other_record.set_time)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, uniqueness: true
  has_many :sleep_ms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/sleep_ms_controller.rb
class SleepMsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_sleep, only: [:show, :edit, :update, :destroy]
  def index
    @sleep_ms = SleepM.all
    if @sleep_ms.present?
      total_sleep_duration = 0
      @sleep_ms.each do |sleep_m|
        total_sleep_duration += sleep_m.sleep_duration_minutes
      end
      average_sleep_duration_minutes = total_sleep_duration / @sleep_ms.length
      @average_sleep_duration_hours = average_sleep_duration_minutes / 60
      @average_sleep_duration_minutes = average_sleep_duration_minutes % 60
    else
      @average_sleep_duration_hours = 0
      @average_sleep_duration_minutes = 0
    end
    @weekly_quality_counts = SleepM.where(created_at: Time.now.beginning_of_week..Time.now.end_of_week)
    .group(:quality).count
  
    # 以下のコードで月ごとの平均睡眠時間を計算
    grouped_sleep_data = @sleep_ms.group_by { |sleep_m| sleep_m.set_time.beginning_of_month }
    @monthly_average_sleep = {}
    grouped_sleep_data.each do |month, sleep_data|
      total_sleep_duration = sleep_data.sum { |sleep_m| sleep_m.sleep_duration_minutes }
      average_sleep_duration_minutes = total_sleep_duration / sleep_data.length
      @monthly_average_sleep[month] = {
        hours: average_sleep_duration_minutes / 60,
        minutes: average_sleep_duration_minutes % 60
      }
    end

    grouped_sleep_data = @sleep_ms.group_by { |sleep_m| sleep_m.set_time.beginning_of_week }
    @weekly_average_sleep = {}
    grouped_sleep_data.each do |week, sleep_data|
      total_sleep_duration = sleep_data.sum { |sleep_m| sleep_m.sleep_duration_minutes }
      average_sleep_duration_minutes = total_sleep_duration / sleep_data.length
      @weekly_average_sleep[week] = {
        hours: average_sleep_duration_minutes / 60,
        minutes: average_sleep_duration_minutes % 60
      }
    end
  end
  
  
  def show
    @sleep_m = SleepM.find(params[:id])
    if @sleep_m.set_time
      @sleep_ms_data = SleepM.where(set_time: @sleep_m.set_time.to_date).order(set_time: :asc)
    else
      @sleep_ms_data = []
    end
  
    respond_to do |format|
      format.html
    end
  end

  def new
    @sleep_m = SleepM.new
  end

  def create
    @sleep_m = SleepM.new(sleep_params)
    if @sleep_m.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @sleep_m = SleepM.find(params[:id])
    if @sleep_m.update(sleep_params)
      redirect_to sleep_m_path(@sleep_m)
    else
      render :edit
    end
  end

  def destroy
    @sleep_m = SleepM.find(params[:id])
    @sleep_m.destroy
    redirect_to root_path
  end

  private

  def set_sleep
    @sleep_m = SleepM.find(params[:id])
  end

  def sleep_params
    params.require(:sleep_m).permit(:set_time, :end_time, :quality, :memo).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sleep_ms_helper.rb
module SleepMsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sleep</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner_o">
        <div class="nav">
        <% if user_signed_in? %>
            <% if @weekly_average_sleep.present? %>
              <ul class="weekly-average-sleep">
                <% @weekly_average_sleep.each do |week, avg_sleep| %>
                  <% if week >= Date.current.at_beginning_of_week && week <= Date.current.at_end_of_week %>
                    <li>
                      <%= week.strftime("今週の平均睡眠時間") %>: <%= avg_sleep[:hours] %>時間<%= avg_sleep[:minutes] %>分
                    </li>
                  <% end %>
                <% end %>
              </ul>
            <% end %>
            <% if @weekly_quality_counts.present? %>
              <p>今週の睡眠の質の回数</p>
              <ul>
                <% SleepM.qualities.keys.each do |quality| %>
                  <li><%= "#{quality}: #{@weekly_quality_counts[quality].to_i}" %>回</li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
            <% if !user_signed_in? %>
                <h2 class="app-title">睡眠の重要性</h2>
            <% end %>
          <div class="nav__left">
            <%= link_to image_tag("sleep_man.png", class: :"logo rotate-icon"), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "睡眠管理", new_sleep_m_path, class: :nav__btn %>
            </div> 
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
      <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: '先月'), calendar.url_for_previous_view, remote: true %>
      <%= link_to t('simple_calendar.today', default: '＜今月＞'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view, remote: true %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sleep_ms/_form.html.erb
<%= form_with model: sleep_m, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :set_time, "睡眠開始時間" %><br />
    <%= f.datetime_field :set_time, class: "form__text", id: "sleep_m_set_time" %>
  </div>

  <div class="field">
    <%= f.label :end_time, "睡眠終了時間" %><br />
    <%= f.datetime_field :end_time, class: "form__text", id: "sleep_m_end_time" %>
  </div>

  <div class="field">
    <%= f.label :quality, "睡眠の質" %><br />
    <%= f.select :quality, SleepM.qualities.keys, class: "form__select", id: "sleep_m_quality" %>
  </div>

  <div class="field">
    <%= f.label :memo, "メモ" %><br />
    <%= f.text_area :memo, class: "form__text", id: "sleep_m_memo" %>
  </div>
  
  <div class="actions">
    <%= f.submit "保存する", class: "form__btn"  %>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const set_timeInput = document.getElementById("sleep_m_set_time");
    const end_timeInput = document.getElementById("sleep_m_end_time");

    set_timeInput.addEventListener("input", function() {
      const startTime = set_timeInput.value;
      end_timeInput.value = startTime; 
    });
  });
</script>

app/views/sleep_ms/_sleep.html.erb
<% @sleep_ms.each do |sleep_m| %>
  <div class="sleep-record">
    <p><strong>睡眠開始時間:</strong> <%= sleep_m.set_time %></p>
    <p><strong>睡眠終了時間:</strong> <%= sleep_m.end_time %></p>
    <p><strong>睡眠の質:</strong> <%= sleep_m.quality %></p>
    <p><strong>メモ:</strong> <%= sleep_m.memo %></p>
    <%= link_to "詳細を見る", sleep_m, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sleep_ms/edit.html.erb
<div class="main">
  <div class="form__wrapper">
    <h2>睡眠記録を編集</h2>
    <%= render partial: "form", locals: { sleep_m: @sleep_m } %>
    <%= link_to "詳細に戻る", sleep_m_path(@sleep_m), class: "btn btn-secondary" %>
  </div>
</main>

app/views/sleep_ms/index.html.erb
<div class="random text-center">
  <% random_messages = ["睡眠時間は1時間30分刻みを意識しましょう", "睡眠前のカフェイン摂取やスマホなどを見ることは睡眠の質低下に繋がりやすいです", "理想はリラックスして眠りに就くこと、運動や勉強から少し時間を置いて寝ましょう"] %>
  <h3><%= random_messages.sample %></h3>
</div>
<main class="main">
  <div class="calendar-container <%= user_signed_in? ? 'left-half' : 'centered' %>">
    <%= month_calendar sleep_ms: @sleep_ms do |date, sleep_ms| %>
      <div class="<%= 'saturday' if date.saturday? %><%= 'sunday' if date.sunday? %>">
        <%= date.day %>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
   <div class="inner">
      <div class="greeting">
        <%= "こんにちは、#{current_user.nickname} さん"  %>
      </div> 
        <% if @monthly_average_sleep.present? %>
          <ul class="monthly-average-sleep">
            <% @monthly_average_sleep.each do |month, avg_sleep| %>
              <li>
                <%= month.strftime("%Y年%m月の平均睡眠時間") %>: <%= avg_sleep[:hours] %>時間<%= avg_sleep[:minutes] %>分
              </li>
            <% end %>
          </ul>
          <h2>詳細一覧</h2>
          <% @sleep_ms.each do |sleep_m| %>
            <p><%= sleep_m.set_time.strftime('%Y年%m月%d日 睡眠開始時間 %H:%M:%S') %> - <%= link_to "詳細を見る", sleep_m_path(sleep_m) %></p>
          <% end %>
        <% end %>
   </div>
  <% end %>
</main>

app/views/sleep_ms/new.html.erb
<div class="main">
  <div class="inner-form">
    <div class="form__wrapper">
      <h2 class="page-heading">睡眠記録記入</h2>
        <%= render partial: "form", locals: { sleep_m: @sleep_m } %>
    </div>
  </div>
</div>

app/views/sleep_ms/show.html.erb
<main class="main">
  <div class="sleep-details">
      <h2>睡眠記録詳細</h2>
        <p><strong>日付:</strong> <%= @sleep_m.set_time.to_date.strftime('%Y年%m月%d日') %></p>
        <p><strong>睡眠開始時間:</strong> <%= @sleep_m.set_time.strftime('%H:%M:%S') %></p>
        <p><strong>睡眠終了時間:</strong> <%= @sleep_m.end_time.strftime('%H:%M:%S') %></p>
        <p><strong>睡眠の質:</strong> <%= @sleep_m.quality %></p>
        <p><strong>メモ:</strong> <%= @sleep_m.memo %></p>
        <%= link_to "編集", edit_sleep_m_path(@sleep_m), class: "btn btn-primary" %>
        <%= link_to "戻る", sleep_ms_path, class: "btn btn-secondary" %>
        <%= link_to "削除", sleep_m_path(@sleep_m), data: { turbo_method: :delete }, class: "btn btn-danger" %>
  </div>
</main>